server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: neo_route
          uri: http://httpbin.org/
          predicates:
            - Path=/get
          filters:
            - AddRequestParameter=a, b
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'